hawkthorne/hawkthorne-journey

src/npcs/hilda.lua, src/npcs/juanita.lua, src/npcs/quests/hildaquest.lua, src/npcs/quests/juanitaquest.lua, src/quest.lua
Adding new collection quests should be dead simple now.
Additionally, expanding the module to permit other types of quests can be accomplished by adding to testSuccess and completeQuestSucceed.
Let me know if there are any features you want me to add before we merge this.
=> Add Quest module and migrate existing quests

make.ps1
This allows for extra arguments to be added to ```./make.ps1 run``` which are then passed to the hawkthorne file. For example, ```./make.ps1 run --console -b -l forest``` is now possible, and is equivalent to ```.\bin\love-0.9.1-win32\love.exe src --console -b -l forest```.
=> Powershell arguments

src/main.lua
No reason not to do this now and it's been around for a while. Re: #2076
=> Lock version to 0.9.1

src/blackjackgame.lua
The "Deal" button wasn't properly disabled when cards were still animating. This allowed players to spam the button even when they had busted, causing them to circumvent the money decrement and not lose money on a losing hand.
I guess my editor found some whitespace to remove as well.
=> Blackjack Bust Exploit

src/player.lua
Fixes the issue pointed out in a comment in #2247 ,
To reproduce follow the instructions laid out by @l3france . 
This issue was caused by checking if standing is possible before velocity/position were changed, this moves the standing code to a more reasonable location.
=> Fix to shooting up through floor in forest

src/tokens/health.lua
Self explanatory. The previous value was left over from before we scaled the player's health.
=> Increase value of hearts

src/maps/hallway.tmx, src/nodes/ceiling_hippy.lua
I'm making this pull request primarily for the purpose of displaying some techniques to make the hippies less frustrating and more fun to play.
Ideally this would merged together with #2307 before being merged into master but that is up for debate.
The purpose here is not to nerf the hallway but to make the hippies feel more like they did in the episode and provide a gentler entry into hawkthorne for first timers.
Me and @niamu were discussing on irc what we could do to improve the feel of the hallway, without making it to easy. Below is a list of those ideas that I have implemented in this branch.
* Warn the player about an imminent hippy by dropping a tile with a delay before the actual hippy attacks 
* Remove non-ceiling hippies (as this is what was seen in the episode, but doesn't …
=> Improve hippies in hallway

src/inventory.lua, src/items/consumables/deepfrieddud.lua
As discussed in #2317, this resolves the bizarre problem of the item type we are about to craft being overwritten by the item subtype if you drop that same item from your inventory prior to crafting it again.
I have no idea why this happens as we are requiring new data from the same file every time. It makes no sense and hence the ugly hack.
Also resolves the deep fried dud string/number comparison crash.
=> Crafting weapons of subtype fix

src/nodes/building.lua, src/nodes/fire.lua
Resolves #2339.
It may not be the most elegant fix in the world, but it gets the job done. We only burn the top two middle tiles of any building to start with. This shouldn't look too terrible even if it is expanded to straight roof buildings in the future.
=> Fire no longer floats above burning building

src/maps/test-level.tmx
The breakable_blocks in the test level were using the old method of sprite names, which was causing it blue screen immediatly.
=> Test level broken

src/npcs/juanita.lua, src/npcs/quests/hildaquest.lua, src/npcs/quests/juanitaquest.lua, src/quest.lua
Check for quests that have already been completed. If they have been completed, give congratulations message without rewards.
Hilda's flower quest now has "infinite = true" as an attribute to allow it to be completed many times. Juanita's quest can only be completed once. However we need to make a choice to either not allow the bottles to respawn on entering the level again or only allow the quest to be taken again if there are bottles to pick up in the level. What should the decision be for that?
=> Allow infinite quests optionally, but not default

src/player.lua
If you hit the ATTACK key while wielding a weapon, the weapon will stay in an attack state. Fixed this by returning the animation to the default state on player refresh.
=> Weapon returns to default position between levels

src/player.lua
This fixes the case where the player is crouching and jumps up through the roof, it does not fix the same situation when the player is in a crawlspace.
=> Prevent popping through roofs

src/nodes/npc.lua, src/player.lua
Everyone always comments about wanting to scroll through the list of Hilda's menu by holding down a key or a button.
Player can't move if a dialog is open on screen. This specifically solves the problem of players still being able to move around in the Tavern when the "Let's play poker" dialog appears.
=> Menus can be scrolled by holding down a key

src/dialog.lua, src/nodes/dealer.lua
Resolves #2363. I initially thought this was going to be a lot more complicated than it turned out to be. On the dealer leave function, we check to see if the dialog is open. If it is, we close it.
=> Close dealer dialog on leaving level

src/board.lua, src/player.lua
Resolves #2361 which is a bug I previously created trying to have the player not move when a
dialog is open.
=> Board manages player control state

src/nodes/consumable.lua, src/nodes/material.lua, src/nodes/projectile.lua, src/nodes/rangedWeapon.lua, src/nodes/scroll.lua, src/nodes/weapon.lua
When dropping an item into a level, wait until it has completely stopped moving before adding it to the gamesave. This means the final position of the item is saved and restored rather than just the initial floor_pushback position.
This also resolves an issue reported by @LoubiTek in the subreddit where dropping an item in a level and immediately picking it back up will cause it to respawn in that same spot if you return to that level.
=> Improve item persistence

src/playerEffects.lua
When potions are loaded from save, their keys are now strings rather than numbers due to the JSON encode/decode process.
So we have to check for the correct type and change it as needed. Resolves #2300.
=> Fix broken dud potions when loaded from save

src/nodes/vehicle.lua, src/player.lua
Resolves #2365. If we are changing levels to a new level, make sure we drop our holdable. Otherwise, pick it up again. It's important to pickup the item again so that positions are reset in the event of a costume change.
=> Drop holdables when changing levels

src/maps/valley-sandpits-2.tmx, src/nodes/climbable.lua
fixes #2362 
This currently drops the player if they collide with spikes while climbing.
I like this as a mechanic but it would be possible to fix this bug without dropping the player in case others don't like it.
=> Prevent popping through roof while climbing into spikes

src/nodes/consumable.lua, src/nodes/material.lua, src/nodes/scroll.lua
When dropping materials, consumables and scrolls in floor spaces the bounding box offset is wrong, this ensures the bounding box is directly over the items.
=> Fix bbox offset when dropping in floorspaces

src/nodes/ceiling_hippy.lua
This resolves the narrow case where a player leaves the level before a hippy is about to drop, causing a crash.
=> Ceiling hippy will only drop if still in level

src/maps/valley-sandpits.tmx, src/nodes/bouncer.lua
fixes #2366 
This allows enemies to bounce on webs, which is pretty hilarious in the sandpits.
The bouncer class was explicitly preventing from enemies from bouncing on it so I think this may be a change we want to discuss before merging in.
=> Allow enemies to bounce on webs

src/player.lua
There's an issue where the player can slide into a crawling tunnel and when they attempt to jump it will pop them up through the roof.
The best way to test this is the tunnel in the forest, run towards the entrance and slide into it without crawling, if you attempt to jump it will pop the player through the roof.
=> Prevent player from jumping in crawl tunnels

src/board.lua
We were returning player controls a bit early as a dialog is starting to close rather than completely closed.
Resolves #2385.
=> Floorspace shadow is locked until dialog is closed

src/nodes/key.lua, src/nodes/spawn.lua
Resolves #2380.
As of right now, we don't currently have any keys that are inside chests, but proposed levels are doing that and having multiple prompts as a result.
This change only shows the chest message on keys spawning from chests.
=> Key messages don't show from chests

src/conf.lua, src/inputcontroller.lua, src/instructions.lua, src/main.lua, src/vendor/gamestate.lua
Resolves #1978 regarding global keys for selecting and going back.
It's not a perfect solution as `ENTER` will now always function as `JUMP`. But that's not exactly a problem.
This change also starts to cleanup some dead code and add the beginnings of the structure necessary for gamepad control support (#2356).
=> Controller support and Global keys

.travis.yml, Makefile, src/main.lua
Previous "fix" wasn't quite correct. LÖVE v0.9.2 is out now and Travis uses that version which we don't allow. This change allows us to make use of versions v0.9.1 and up.
Inexplicably, Travis fails when executing code in the Makefile to install love, but succeeds when that same code is moved to .travis.yml. I'm not questioning that, this seems to work so I'm going with it.
=> Travis CI fixes

src/maps/castle-hawkthorne-entrance.tmx, src/maps/castle-hawkthorne-throne.tmx
This detaches the interior rooms of castle hawkthorne from the throneroom.  Right now there's not much going on in those rooms.  All they contain are semi working vehicles and empty rooms.  In the future this should be much more complicated so for the V1.0 release I've connected the entrance to the throneroom.
=> Detach the interior castle from the throneroom

templates/conf.lua
Our build process uses a different `conf.lua` template that had the joystick module disabled for releases. That explains our issue, #2400.
=> Controller module enabled for releases

src/options.lua
Currently only the first save is reset when reset all saves is selected.
=> Fix save reset in options

src/inventory.lua, src/nodes/consumable.lua, src/nodes/material.lua, src/nodes/projectile.lua, src/nodes/rangedWeapon.lua, src/nodes/scroll.lua, src/nodes/weapon.lua
No idea why the sound was disabled in the first place, but this will definitely help with audible feedback for players and give an error sound for when inventory is full and pickup fails.
=> Enable item pickup sounds

src/maps/town.tmx
Player can no longer get stuck in release/grab loop by helding UP and LEFT. Resolves. #2384.
This is a cheap and easy solution that appears to work for me. I just make the ladder width much narrower which gives the player enough room on the left side of the ladder to keep walking left without starting to fall and then re-grab the ladder.
This could also be fixed by extending the platform to the left a little more, but then there's a spot that the player can stand on which appears to be hovering in mid-air.
If this breaks for someone else, I vote that we just close the issue.
=> Ladder in town improvement

src/hawk/collision.lua
This should fix the [issue pointed out in the subreddit](http://www.reddit.com/r/hawkthorne/comments/379mgq/still_falling_through_platforms_in_village_forest/).
I seems that some people were still having trouble with vertically moving platforms, I was never able to reproduce this but I do fall through when standing up from a crouch while the platform is moving up, this fixes that issue for me and should fix the issue pointed out in the above post.
=> Prevent player from falling through moving platforms (Hopefully)

src/nodes/breakable_block.lua
There is sometimes an issue when placing sloped breakables that causes the tile to place in the wrong location.
=> Fix sloped breakable offseting issue

src/nodes/npc.lua
Interact with Hilda just before she notices the burning building and her menu will stay open.
This change, closes any NPC menu if they are busy.
=> NPCs close their menus when they become busy

src/pause.lua
Currently I just play the double beep sound effect if you're in hardcore mode and try to select the menu item. Probably not the most obvious feedback, but it is effective.
=> Disable overworld in hardcore mode

src/nodes/token.lua
Token value was being erroneously taken from the spawn source instead of from the token's file.
Hearts should actually be useful now!
=> Fix token value

src/items/weapons/arrow.lua, src/items/weapons/icicle.lua, src/items/weapons/throwingaxe.lua, src/items/weapons/throwingknife.lua
This increases the amount that projectiles can stack in the inventory.  Originally this number was low to prevent stocking the inventory and to forced the player to switch between stacks of projectiles.  Since opening the inventory pauses enemies it's only annoying to switch between small stacks of projectiles.
=> Up projectile stacking limit.

src/nodes/enemies/tSnake.lua
Previously it was tied to the player's location.
=> Lock down the spawn location of the snake key

src/player.lua
Currently there are particular cases where while wearing armor the player will take negative damage effectively healing them by a small amount. This pull guarantees that the smallest damage taken is 0.
=> Prevent player from "healing" when hurt

src/nodes/projectiles/waterSpout.lua
Resolves the important parts of #2470. I'm not going to touch the fact that you can shoot a water spout while you're jumping or otherwise in the air because that will mean modifying too many other core components of the game.
=> The Epic's water spout dies hitting a wall

src/nodes/bouncer.lua
Resolves #2463 where it was discovered that the player attack node attempts to collide with the bouncer node and because it has some non-standard attributes, compared to most other nodes, it crashes the game.
No need to have it interact with the bouncers anyways, so now it doesn't.
=> Player attack node no longer collides with bouncer

src/player.lua
#2461 makes no sense. There are some cases where the `map` property doesn't get properly passed from `level.lua` to `player.lua`. This should never happen and I can't explain why it happens. I blame LÖVE.
=> Sometimes level.map mysteriously doesn't exist???

src/overworld.lua
After playing through the game and watching many many play-throughs I've started to think about the overworld map checkpoints.  With the expansion of the Village-Forest we've added 12 new levels to that area.  Because of this the placement of the second Village-Forest overworld checkpoint became sort of useless.  I've moved the checkpoint so it goes to village-forest-2 (the level where Tilda is).  I think this is a more useful central location for the checkpoint.
=> Move Overworld Checkpoint to more useful central location

src/maps/black-caverns.tmx
There was an issue posted on the [subreddit](https://www.reddit.com/r/hawkthorne/comments/3bmj09/black_caverns_disappearing_bug/) where the player disappears when they hit the spikes in the top left of black-caverns, this prevents the platform from going as high so that it doesn't push the player into the blocks.
=> Don't push player through ceiling in black-caverns

src/hawk/collision.lua, src/nodes/movingplatform.lua
I think this is the second or third time I've fixed this bug, this time I'm fairly certain we've got it this time.
Before this bug was fixed, but with the addition of some faster platforms in the recent village-forest upgrade this issue has come back, We now take the platforms dy value into consideration when placing the player on one so this should continue working even if we add faster platforms.
I also fixed a bug where if the player attempted to drop while on a moving platform and then jumped onto a one-way they would fall through as if they had dropped.
A good place to test either of these issues is village-forest.
=> Player still dropping through moving platforms

src/maps/hallway.tmx, src/maps/house.tmx, src/nodes/door.lua, src/nodes/hiddendoortrigger.lua
This fixes a bug where no image for hidden doors was showing when re-entering a level.
Additionally I think it's nicer to alert the player that the door is hideable.
To test this open the fireplace in the house and then leave the level and come back.
This also slows down up the greendale door becuase it now plays the sound every time which was weird without an animation.
=> Play the show door animation when entering level

src/main.lua
Gamepad input was previously firing as both gamepad and joystick. This hopefully resolves the problem without breaking joystick support.
@8bitgentleman can hopefully confirm.
=> Gamepad input is only fired once

.travis.yml, requirements.txt
Our current release attempts break and give out this error as as result:
https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning
This is my attempt at a fix, and hopefully resolution to the release builds.
=> Python library updates

src/nodes/door.lua
This fixes doors still obstructing the player after the door was opened.
=> Fix obstructing door

src/nodes/enemies/benzalkBoss.lua
After the player respawns after being killed by Cornelius they tend to inexplicably dance, as noted [here](https://www.reddit.com/r/hawkthorne/comments/3qd4ec/what_happened_to_cornelius/). This was caused by benzalk loading and immediately calling die. This had been fixed using the hide argument of the die function which was put there for this situation.
Also this is the first pull on a new computer so excuse the file ending.
=> Prevent player from celebrating after being killed by Cornelius

Makefile, templates/post.md
We have failures in our current releases related to pushing to GitHub. Rather than attempt to fix the problem, this just works around it by not pushing to GitHub anymore during a release and therefore releases will need to be a manual process going forward for now.
=> GitHub workaround for releases

src/blackjackgame.lua
-Fixed bet increment/decrement logic. Will allow player to max out bet to available money. When decrementing the bet, will remove the portion not part of the standard decrement, if not a multiple of that decrement.
-Fixed the gameMenu logic regarding when to allow splits and double downs, as related to player money and the current wager. Existing logic would not allow a double down or split under certain conditions (e.g., when trying to double down after splitting, could not double down if player money was not at least 4x greater than the current bet, logic should actual check if player is capable of adding another currentBet to wager).
-Fixed dealer winning on blackjack even if player has blackjack. Now it's a push if player also has blackjack.
=> Blackjack bug fixes

src/nodes/insults.lua
The insult for Fat Neil was misspelled and would crash the Cornelius boss fight.
=> Fix Fat Neil Insult Spelling

src/inputcontroller.lua, src/test/test_inputcontroller.lua
As of LÖVE 0.9.2, the KeyConstant for spacebar is no longer `" "` but `"space"`.
This was causing a fresh boot of the game to not register spacebar inputs on Linux (tested from Fedora 24 with LÖVE 0.10.0).
A workaround was to reset the controls from the controls menu. This just isn't very obvious as the controls menu already says "space/enter" for jump, even when space is unresponsive.
I figured since Hawkthorne targets LÖVE 0.10.0, it would be fitting to upgrade to the new space constant.
=> Update inputcontroller to LÖVE >0.9.2 space key

src/cheat.lua, src/items/potion_recipes.lua
'Bubblegum' is currently spelled 'bubblgum', and this misspelling is causing crashes: https://www.reddit.com/r/hawkthorne/comments/95clnx/i_found_a_glitch_in_the_cheats_menu_this_message/
=> Fix misspelling of bubblegum ("bubblgum")

src/hawk/collision.lua, src/level.lua, src/player.lua
The first is when you attack soon after crouching. If you timed it just right, attacking just before you went under a low ceiling would cause you to stand up and clip into the ceiling.
The second, which is related to the first, would happen if you stood up right at the edge of a ceiling. The code would find a tile above the character instead of below, since even when standing still, gravity causes the collision code to run assuming you're falling down.
Both of these situations are easiest to reproduce when on a moving platform.
I tested this extensively with `--level=black-caverns-2 --cheat=give_master_key`: 
- Jump onto the moving platform  
- Right before you pass under the edge of the ceiling, crouch -> stand -> attack  
- Another test is to hit down + up very fast right near the edge …
=> Addresses two common collision issues

src/nodes/npc.lua, src/tooltip.lua, src/vendor/tastytext/init.lua
Resolves https://github.com/hawkthorne/hawkthorne-journey/issues/2596
Also moved inventory display into the NPC dialog callback function for a slightly cleaner screenshot.
=> TastyText line length fix for love.js

Makefile, templates/web/index.html, templates/web/love-game.js
[love.js](https://github.com/Davidobot/love.js) does have full support for v11.5, but it hasn't been published to NPM yet. In the meantime I have a temporary workaround where we download `love.js` and `love.wasm` directly from the repository.
I've also updated `love-game.js` to support relative URL dependency loading.
=> love.js v11.5 and relative dependency loading

CONTRIBUTORS, Makefile, scripts/credits.py, src/credits.lua, templates/linux/Hawkthorne.metainfo.xml
Created for Flathub submission in https://github.com/flathub/flathub/pull/5877, see also https://github.com/hawkthorne/hawkthorne-journey/issues/2588
AppStream specification documentation: https://www.freedesktop.org/software/appstream/docs/
=> Add Linux AppStream metadata

CONTRIBUTORS, Makefile, src/conf.lua, src/credits.lua, src/shopping.lua
[Reported in the subreddit](https://www.reddit.com/r/hawkthorne/comments/1gyqoj8/glitched_the_blacksmith/)
Best guess is some sort of race condition that this change should now prevent.
=> Guard against shopping crash
