.travis.yml
Testing to see if this fixes the current problem with Travis
=> Remove unzip from Travis apt-get

Makefile
There aren't any fully packed versions of .deb so we'll just make do for now
Game will break on release of a newer version of love2d
=> Get Love 9.0.1 for OSX

src/maps/hallway.tmx, src/nodes/enemy.lua
=> Enemy splats are now covering the hidden door

src/maps/forest-hidden.tmx, src/maps/forest.tmx, src/maps/valley-3.tmx, src/maps/valley-chili-fields.tmx, src/maps/valley-sandpits-2.tmx, src/maps/valley-sandpits.tmx, src/nodes/breakable_block.lua
Also removes the need for '.png' in the properties for breakable blocks.
~~I promise I'll stop getting distracted and get the hud and potion recipes finished tomorrow.~~
=> Add's Pierce's little hole in forest

src/hawk/collision.lua
Should fix the first two issues pointed out by a reddit user [here](https://github.com/hawkthorne/hawkthorne-journey/issues/2247#issuecomment-61226490).
=> Collision issues

src/nodes/enemies/hippy.lua, src/nodes/enemy.lua
Enemies can now play sounds randomly (defined as chance per second) while their state is default and they are on screen. This has been implemented for hippies, which now randomly say 'peace'. On a side note we should get a 'love' sound effect for the hippies.
=> Passive noises for enemies.

src/hawk/collision.lua
I was only able to duplicate this while using the super speed cheat on the slopes of valley.tmx (the slopes in the top right).
fixes issue pointed out be @edisonout  @l3france in #2247
=> Fix falling through floors

src/nodes/throwable.lua, src/nodes/vehicle.lua, src/player.lua
=> Costume changes while holding items/vehicles

src/nodes/enemies/turkeyBoss.lua
=> Turkey gobble stops after player or boss dies

src/player.lua, src/quest.lua
=> Save and load quests

src/pokergame.lua
Refer to [this post on the subreddit](http://www.reddit.com/r/hawkthorne/comments/1a8tw9/poker_kickers_arent_working_properly/) for details.
Someone just missed a counter in their while loop a long time ago. Resolves one of the issues in #2322.
=> Poker kickers

src/maps/greendale-englishmemorial.tmx, src/maps/vents.tmx
Ladies room key is now saved when you enter the vents so it doesn't matter if you die. All monkey gas now kills you. Fixed a few collision tiles in English memorial.
Partially fixes #2328 
Appparently the new version of tiled is adding id tags to everything.
=> Key for Ladies Room and English Memorial fixes

src/nodes/enemy.lua
=> Pause enemies when inventery is open

src/level.lua, src/player.lua
=> Stop player falling through floor on character switch

src/player.lua
Make sure we go through :die() function when health reaches 0 inside :update()
Reset x-axis velocity when taking fall damage.
Resolves #2353.
=> Improve fall damage

src/nodes/enemy.lua
@8bitgentleman has expressed a need for this a few times and will help him with #2347 and #2233.
This will likely require more testing, but this allows enemies to attack and deal damage to breakable blocks.
I tested this by adding one of the breakable blocks from the forest into the hallway level. Hippies attack the block until it is broken and then proceed as normal. The process should be similar for all other enemies.
=> Enemies can attack breakable blocks

src/maps/valley-tacotown.tmx
Just a simple pull to add a potion brewer to Tacotown, I don't even know why it's not there in the first place
=> Add cauldron to valley

.travis.yml, Makefile
Don't ask me why this fixes things, but it does. I'm just going with it.
=> Travis CI fixes

src/maps/castle-hawkthorne-entrance.tmx
As noted in the subreddit by [Thom_Ryan](http://www.reddit.com/r/hawkthorne/comments/37bqeg/castle_door/).
=> Reposition Castle Door so player can't go behind

src/nodes/spawn.lua
Added spawn saving which prevents people from abusing chests to get unlimited rewards.
=> Spawn Saving

src/nodes/enemies/turkeyBoss.lua
=> Turkey Boss only hatches once

src/main.lua
Requested by @8bitgentleman, This will be useful for testing things that frequently get saves (eg quests).
=> Add command line argument to reset saves

src/player.lua
Shows the actual damage now.
Also shows a 0 when armor has blocked all the damage.
=> Fix damage text

src/hud.lua, src/quest.lua
This fixes the error with Frankie's "remove bone quest" where she'll accept the quest as being finished even if you didn't collect all the bones
=> fix removeall quest type

scripts/version.py
Use "MAJORVERSION" in the pull title to up the major version number, just like "RELEASE" updates the minor version.
Someone take a look and make sure this looks right.
=> Update version.py for major version

scripts/version.py
My bad.
This should fix the build error. Hey, at least we know it's using the right function.
=> Fix int bug in major version

scripts/version.py, src/hud.lua
It's the big one, boys and girls.
*Fingers crossed*
=> MAJORVERSION 1.0.0

src/maps/valley-3.tmx
I left that there for testing purposes, my bad.
=> Removed QFO from valley-3

src/main.lua
=> When controller is removed, revert to keyboard

src/cheat.lua, src/inventory.lua, src/maps/gay-island.tmx, src/nodes/enemies/cornelius.lua, src/nodes/projectile.lua, src/nodes/projectiles/waterSpout.lua, src/nodes/weapons/epic.lua, src/npcs/alien_regroup.lua, src/suppliers/mysteryvendor.lua
I've marked off several items in #2452 that this pull request will resolve.
=> Assorted bugfixes for v1.0

src/nodes/door.lua
Resolves #2467.
I'm not sure if this breaks anything else, so please feel free to test this on several doors.
=> Player can jump through door

.travis.yml, Makefile, scripts/productionize.py
=> Enable Travis CI artifacts

.travis.yml
I'm not sure if this is exactly right, but following the [instructions](http://docs.travis-ci.com/user/encryption-keys/) this seems like it might securely resolve our posting to Reddit problems.
Right now I've just added them through the web UI, but I don't think that's as secure as this is. Worth a shot.
=> Travis ENV variables for britta-bot

.travis.yml
I've moved all the necessary secrets into environment variables in Travis.
=> Remove secrets from travis.yml

src/cheat.lua, src/maps/hallway.tmx, src/nodes/enemies/cornelius.lua
Cornelius won't appear when the "greendale is where i belong" cheat is activated. This fixes that by adding a seperate trigger for opening greendale.
=> Fix cornelius not appearing with certain cheat

src/inventory.lua, src/nodes/building.lua, src/nodes/enemies/acornBoss.lua, src/nodes/enemies/laserlotusBoss.lua, src/nodes/enemies/qfo.lua, src/nodes/mailbox.lua, src/npcs/alien.lua, src/npcs/frankie.lua, src/npcs/hermit.lua, src/npcs/jerry.lua, src/npcs/oldman.lua, src/npcs/quests/alienquest.lua, src/npcs/quests/frankiequest.lua, src/npcs/quests/tildaquest.lua, src/npcs/telescopejuan.lua, src/npcs/tilda.lua, src/quest.lua
I believe this resolves the remaining issues with #2452.
Every quest in the game now uses the quest module (if not completely correctly) so that we should never have a problem with adding or removing a quest again. Quest issues were the core problem to the QFO and the Acorn King spawning issues as well.
=> V1 bugfixes

src/maps/village-forest-stonerspeak-return.tmx, src/npcs/hermit.lua, src/quest.lua
Should resolve both Hermit and Tilda quest issues.
=> Save quests when adding or removing

src/nodes/enemies/qfo.lua
Fixes the line that was mistakenly removed.
=> fix qfo health being refilled

src/npcs/blacksmith_wife.lua, src/npcs/jerry.lua, src/npcs/laserlotus1.lua, src/npcs/profholly.lua, src/npcs/quests/hildaquest.lua, src/npcs/quests/juanitaquest.lua, src/npcs/senorjuan.lua, src/npcs/telescopejuan.lua
Thanks to @LoubiTek for pointing out the minor errors in some of the npc dialogue. The removal of a single space wasn't worth the individual commit/pull request he created for each file so I've combined them all here. It's still a thoroughly underwhelming pull request.
=> Fix minor spacing issues in npc dialogue

src/maps/gazette-office.tmx, src/npcs/shmitty.lua
Addresses the issues brought up in [this](https://www.reddit.com/r/hawkthorne/comments/3qucsr/guys_i_found_another_bug_explanation_in_comments/) subreddit post.
=> Fix shmitty text and gazette office floorspace

.travis.yml, Makefile, make.ps1, src/characterstrip.lua, src/conf.lua, src/fonts.lua, src/hud.lua, src/main.lua, src/maps/town.tmx, src/nodes/enemies/acornBoss.lua, src/nodes/enemies/benzalkBoss.lua, src/nodes/enemies/laserlotusBoss.lua, src/nodes/enemies/qfo.lua, src/nodes/enemies/tSnake.lua, src/nodes/enemies/turkeyBoss.lua, src/player.lua, src/tooltip.lua, src/tunnelparticles.lua, src/verticalparticles.lua, templates/conf.lua
With 0.10.0 LÖVE officially supports mobile.  This is the first step towards hawkthorne supporting it as well as mentioned in #2543 .  Thanks to @edisonout  and @CalebJohn for the assistance.  Should also close #2546.
=> Update Hawkthorne to LÖVE 0.10.0

Makefile
love 0.10.0 is no longer available.
=> Bump Love to 0.10.1

CONTRIBUTORS
I add my nickname because I feel I have contributed to the research of bugs and adding sounds. I remain on this project to the extent necessary for future assistance.
=> Add loubitek

CONTRIBUTORS
One of the contributors was overlooked and requested that he be added to the list
=> add-pankobro

CONTRIBUTORS, src/nodes/insults.lua
=> fix typo causing #2572

make.ps1
Also added try/catch mechanisms so the script fails if a download fails.
Addresses #2582
=> Update download URLs

src/maps/black-caverns-2.tmx
Resolves https://github.com/hawkthorne/hawkthorne-journey/issues/2542
=> Fix mismatched collision tile in black caverns

src/maps/black-caverns-3.tmx, src/nodes/weapons/epic.lua
Resolves https://github.com/hawkthorne/hawkthorne-journey/issues/2549
=> Epic weapon fixes

src/nodes/npc.lua
Resolves https://github.com/hawkthorne/hawkthorne-journey/issues/2457
=> If player is already frozen, don't allow them to interact with NPC

.github/workflows/build.yml, .github/workflows/deploy.yml, Makefile
Use GitHub Actions to build the game and confirm tests pass. I'll be adding Rulesets which require the Build to pass before any code can be merged.
=> Build and Deploy Workflows
